/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.CadastroFornecedorDAO;
import Dao.CadastroLojaDAO;
import Dto.CadastroFornecedorDTO;
import Dto.CadastroLojaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manenhos
 */
public class CadastroLoja extends javax.swing.JFrame {

    /**
     * Creates new form Cadastroloja
     */
    public CadastroLoja() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(CadastroProdutos.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulocadastrodelojas = new javax.swing.JLabel();
        btLojasl = new javax.swing.JButton();
        btFornecedoresl = new javax.swing.JButton();
        btProdutosl = new javax.swing.JButton();
        txtLoja = new javax.swing.JTextField();
        txtTelefonel = new javax.swing.JTextField();
        txtEmaill = new javax.swing.JTextField();
        txtEnderecol = new javax.swing.JTextField();
        txtTotalvendido = new javax.swing.JTextField();
        iLoja = new javax.swing.JLabel();
        lTelefonel = new javax.swing.JLabel();
        lEmaill = new javax.swing.JLabel();
        lEnderecol = new javax.swing.JLabel();
        lTotalvendido = new javax.swing.JLabel();
        lCondigodaloja = new javax.swing.JLabel();
        txtCodigodaloja = new javax.swing.JTextField();
        btInicial = new javax.swing.JButton();
        btExcluirp = new javax.swing.JButton();
        btConsultarp = new javax.swing.JButton();
        btAlterarp = new javax.swing.JButton();
        btSalvarp = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLoja = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 441));
        setSize(new java.awt.Dimension(630, 441));
        getContentPane().setLayout(null);

        lTitulocadastrodelojas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lTitulocadastrodelojas.setForeground(new java.awt.Color(0, 0, 0));
        lTitulocadastrodelojas.setText("CADASTRO DE LOJAS");
        getContentPane().add(lTitulocadastrodelojas);
        lTitulocadastrodelojas.setBounds(177, 12, 254, 28);

        btLojasl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btLojasl.setText("Lojas");
        btLojasl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLojaslActionPerformed(evt);
            }
        });
        getContentPane().add(btLojasl);
        btLojasl.setBounds(384, 52, 110, 24);

        btFornecedoresl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btFornecedoresl.setText("Fornecedores");
        btFornecedoresl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoreslActionPerformed(evt);
            }
        });
        getContentPane().add(btFornecedoresl);
        btFornecedoresl.setBounds(256, 52, 110, 24);

        btProdutosl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btProdutosl.setText("Produtos");
        btProdutosl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoslActionPerformed(evt);
            }
        });
        getContentPane().add(btProdutosl);
        btProdutosl.setBounds(128, 52, 110, 24);
        getContentPane().add(txtLoja);
        txtLoja.setBounds(76, 114, 437, 25);
        getContentPane().add(txtTelefonel);
        txtTelefonel.setBounds(76, 165, 200, 25);
        getContentPane().add(txtEmaill);
        txtEmaill.setBounds(76, 216, 300, 25);
        getContentPane().add(txtEnderecol);
        txtEnderecol.setBounds(76, 267, 420, 25);
        getContentPane().add(txtTotalvendido);
        txtTotalvendido.setBounds(76, 318, 200, 25);

        iLoja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        iLoja.setText("Loja:");
        getContentPane().add(iLoja);
        iLoja.setBounds(76, 94, 24, 14);

        lTelefonel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lTelefonel.setText("Telefone:");
        getContentPane().add(lTelefonel);
        lTelefonel.setBounds(76, 145, 45, 14);

        lEmaill.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lEmaill.setText("E-mail:");
        getContentPane().add(lEmaill);
        lEmaill.setBounds(76, 196, 34, 14);

        lEnderecol.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lEnderecol.setText("Endereço:");
        getContentPane().add(lEnderecol);
        lEnderecol.setBounds(76, 247, 47, 14);

        lTotalvendido.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lTotalvendido.setText("Total Vendido:");
        getContentPane().add(lTotalvendido);
        lTotalvendido.setBounds(76, 298, 72, 14);

        lCondigodaloja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lCondigodaloja.setText("Código da loja:");
        getContentPane().add(lCondigodaloja);
        lCondigodaloja.setBounds(324, 145, 71, 14);
        getContentPane().add(txtCodigodaloja);
        txtCodigodaloja.setBounds(324, 165, 189, 25);

        btInicial.setBackground(new java.awt.Color(121, 218, 247));
        btInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        btInicial.setBorder(null);
        btInicial.setContentAreaFilled(false);
        btInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btInicial);
        btInicial.setBounds(543, 12, 50, 50);

        btExcluirp.setBackground(new java.awt.Color(121, 218, 247));
        btExcluirp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btExcluirp.setBorder(null);
        btExcluirp.setContentAreaFilled(false);
        btExcluirp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirpActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluirp);
        btExcluirp.setBounds(390, 370, 25, 24);

        btConsultarp.setBackground(new java.awt.Color(121, 218, 247));
        btConsultarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultar.png"))); // NOI18N
        btConsultarp.setBorder(null);
        btConsultarp.setContentAreaFilled(false);
        btConsultarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarpActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarp);
        btConsultarp.setBounds(290, 370, 25, 25);

        btAlterarp.setBackground(new java.awt.Color(121, 218, 247));
        btAlterarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        btAlterarp.setBorder(null);
        btAlterarp.setContentAreaFilled(false);
        btAlterarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarpActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterarp);
        btAlterarp.setBounds(200, 370, 24, 25);

        btSalvarp.setBackground(new java.awt.Color(121, 218, 247));
        btSalvarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_1.png"))); // NOI18N
        btSalvarp.setBorder(null);
        btSalvarp.setContentAreaFilled(false);
        btSalvarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarpActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarp);
        btSalvarp.setBounds(120, 370, 24, 25);

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btSelecionar);
        btSelecionar.setBounds(460, 340, 90, 25);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(460, 370, 90, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundinho_1.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(630, 460));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 670, 440);

        tabelaLoja.setAutoCreateRowSorter(true);
        tabelaLoja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabelaLoja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Loja", "Loja", "Telefone", "E-mail", "Endereço", "Total Vendido"
            }
        ));
        tabelaLoja.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaLojaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelaLoja);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 440, 630, 250);

        setBounds(0, 0, 644, 723);
    }// </editor-fold>//GEN-END:initComponents

    private void btProdutoslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoslActionPerformed
        this.dispose();//fecha o form atual aberto
        CadastroProdutos cdp = new CadastroProdutos();
        cdp.setVisible(true);
    }//GEN-LAST:event_btProdutoslActionPerformed

    private void btLojaslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLojaslActionPerformed
        JOptionPane.showMessageDialog(null, "Você já está no cadastro lojas");
    }//GEN-LAST:event_btLojaslActionPerformed

    private void btFornecedoreslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoreslActionPerformed
        this.dispose();//fecha o form atual aberto
        CadastroFornecedor cf = new CadastroFornecedor();
        cf.setVisible(true);
    }//GEN-LAST:event_btFornecedoreslActionPerformed

    private void btInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicialActionPerformed
        this.dispose();//fecha o form atual aberto
        Controle c = new Controle();
        c.setVisible(true);
    }//GEN-LAST:event_btInicialActionPerformed

    private void btSalvarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarpActionPerformed
        String loja, telefone, email, endereco;
        int codigoloja;
        double totalvendido;

        loja = txtLoja.getText();
        telefone = txtTelefonel.getText();
        email = txtEmaill.getText();
        endereco = txtEnderecol.getText();
        codigoloja = Integer.parseInt(txtCodigodaloja.getText());
        totalvendido = Double.parseDouble(txtTotalvendido.getText());

        CadastroLojaDTO objcadastrolojadto = new CadastroLojaDTO();
        objcadastrolojadto.setLoja(loja);
        objcadastrolojadto.setTelefone(telefone);
        objcadastrolojadto.setEmail(email);
        objcadastrolojadto.setEndereco(endereco);
        objcadastrolojadto.setCodigoLoja(codigoloja);
        objcadastrolojadto.setTotalVendido(totalvendido);

        if (codigoloja == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Código da Loja obrigatório!");
        }
        if (loja.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Loja obrigatório!");
        }
        if (telefone.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Telefone obrigatório!");
        }
        if (endereco.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Endereço obrigatório!");
        }
        if (totalvendido == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Total Vendido obrigatório!");
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do E-mail obrigatório!");
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }

        CadastroLojaDAO objlojadao = new CadastroLojaDAO();
        objlojadao.cadastroLojadao(objcadastrolojadto);

    }//GEN-LAST:event_btSalvarpActionPerformed

    private void tabelaLojaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaLojaAncestorAdded
      
    }//GEN-LAST:event_tabelaLojaAncestorAdded

    private void btConsultarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarpActionPerformed
        listarValoresLoja();
    }//GEN-LAST:event_btConsultarpActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimparCampos();

    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarpActionPerformed
        AlterarCadastroLoja();
        listarValoresLoja();
        LimparCampos();
        
    }//GEN-LAST:event_btAlterarpActionPerformed

    private void btExcluirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirpActionPerformed
        ExcluirCadastroLoja();
        listarValoresLoja();
        LimparCampos();
    }//GEN-LAST:event_btExcluirpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarp;
    private javax.swing.JButton btConsultarp;
    private javax.swing.JButton btExcluirp;
    private javax.swing.JButton btFornecedoresl;
    private javax.swing.JButton btInicial;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLojasl;
    private javax.swing.JButton btProdutosl;
    private javax.swing.JButton btSalvarp;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JLabel iLoja;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCondigodaloja;
    private javax.swing.JLabel lEmaill;
    private javax.swing.JLabel lEnderecol;
    private javax.swing.JLabel lTelefonel;
    private javax.swing.JLabel lTitulocadastrodelojas;
    private javax.swing.JLabel lTotalvendido;
    private javax.swing.JTable tabelaLoja;
    private javax.swing.JTextField txtCodigodaloja;
    private javax.swing.JTextField txtEmaill;
    private javax.swing.JTextField txtEnderecol;
    private javax.swing.JTextField txtLoja;
    private javax.swing.JTextField txtTelefonel;
    private javax.swing.JTextField txtTotalvendido;
    // End of variables declaration//GEN-END:variables

    private void listarValoresLoja() {
        try {
            CadastroLojaDAO objCadastrolojaDAO = new CadastroLojaDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaLoja.getModel();
            model.setNumRows(0);

            ArrayList<CadastroLojaDTO> lista = objCadastrolojaDAO.pesquisarCadastroLoja();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    
                    lista.get(num).getLoja(),
                    lista.get(num).getCodigoLoja(),
                    lista.get(num).getTelefone(),
                    lista.get(num).getEmail(),
                    lista.get(num).getEndereco(),
                    lista.get(num).getTotalVendido()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores tela Loja" + e.getMessage());
        }
    }

    private void AlterarCadastroLoja(){
        String loja, telefone, email, endereco;
        int codigoloja;
        double totalvendido;

        loja = txtLoja.getText();
        telefone = txtTelefonel.getText();
        email = txtEmaill.getText();
        endereco = txtEnderecol.getText();
        codigoloja = Integer.parseInt(txtCodigodaloja.getText());
        totalvendido = Double.parseDouble(txtTotalvendido.getText());

        CadastroLojaDTO objcadastrolojadto = new CadastroLojaDTO();
        objcadastrolojadto.setLoja(loja);
        objcadastrolojadto.setTelefone(telefone);
        objcadastrolojadto.setEmail(email);
        objcadastrolojadto.setEndereco(endereco);
        objcadastrolojadto.setCodigoLoja(codigoloja);
        objcadastrolojadto.setTotalVendido(totalvendido);
        
        CadastroLojaDAO objlojadao = new CadastroLojaDAO();
        objlojadao.alterarCadastroLoja(objcadastrolojadto);
    }
    
     private void ExcluirCadastroLoja(){
        String loja, telefone, email, endereco;
        int codigoloja;
        double totalvendido;

        loja = txtLoja.getText();
        telefone = txtTelefonel.getText();
        email = txtEmaill.getText();
        endereco = txtEnderecol.getText();
        codigoloja = Integer.parseInt(txtCodigodaloja.getText());
        totalvendido = Double.parseDouble(txtTotalvendido.getText());

        CadastroLojaDTO objcadastrolojadto = new CadastroLojaDTO();
        objcadastrolojadto.setLoja(loja);
        objcadastrolojadto.setTelefone(telefone);
        objcadastrolojadto.setEmail(email);
        objcadastrolojadto.setEndereco(endereco);
        objcadastrolojadto.setCodigoLoja(codigoloja);
        objcadastrolojadto.setTotalVendido(totalvendido);
        
        CadastroLojaDAO objlojadao = new CadastroLojaDAO();
        objlojadao.excluirCadastroFornecedor(objcadastrolojadto);
    }
     
    private void CarregarCampos(){
        int setar = tabelaLoja.getSelectedRow();
        txtCodigodaloja.setText(tabelaLoja.getModel().getValueAt(setar,1).toString());
        txtLoja.setText(tabelaLoja.getModel().getValueAt(setar, 0).toString());
        txtTelefonel.setText(tabelaLoja.getModel().getValueAt(setar, 2).toString());
        txtEmaill.setText(tabelaLoja.getModel().getValueAt(setar, 3).toString());
        txtEnderecol.setText(tabelaLoja.getModel().getValueAt(setar, 4).toString());
        txtTotalvendido.setText(tabelaLoja.getModel().getValueAt(setar, 5).toString());
    }
    private void LimparCampos(){
        txtCodigodaloja.setText("");
        txtLoja.setText("");
        txtTelefonel.setText("");
        txtEmaill.setText("");
        txtEnderecol.setText("");
        txtTotalvendido.setText("");
        
    }
}
