/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.CadastroProdutosDAO;
import Dto.CadastroProdutosDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manenhos
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form Funcionario
     */
    public CadastroProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(CadastroProdutos.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulocadastrodeprodutos = new javax.swing.JLabel();
        btProdutosp = new javax.swing.JButton();
        btFornecedoresp = new javax.swing.JButton();
        btLojasp = new javax.swing.JButton();
        lItem = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        lCodigoproduto = new javax.swing.JLabel();
        txtCodigodoproduto = new javax.swing.JTextField();
        lUnidadedemedida = new javax.swing.JLabel();
        txtUnidadedemedida = new javax.swing.JTextField();
        lEstoqueminimo = new javax.swing.JLabel();
        txtEstoqueminimo = new javax.swing.JTextField();
        lCustounitario = new javax.swing.JLabel();
        txtCustounitario = new javax.swing.JTextField();
        lPrecounitario = new javax.swing.JLabel();
        txtPrecounitario = new javax.swing.JTextField();
        btSalvarp = new javax.swing.JButton();
        btAlterarp = new javax.swing.JButton();
        btConsultarp = new javax.swing.JButton();
        btExcluirp = new javax.swing.JButton();
        btInicial = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(630, 441));
        setMinimumSize(new java.awt.Dimension(650, 460));
        setPreferredSize(new java.awt.Dimension(630, 460));
        setSize(new java.awt.Dimension(630, 441));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitulocadastrodeprodutos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lTitulocadastrodeprodutos.setForeground(new java.awt.Color(0, 0, 0));
        lTitulocadastrodeprodutos.setText("CADASTRO DE PRODUTOS");
        getContentPane().add(lTitulocadastrodeprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 12, -1, -1));

        btProdutosp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btProdutosp.setText("Produtos");
        btProdutosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutospActionPerformed(evt);
            }
        });
        getContentPane().add(btProdutosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 52, 110, -1));

        btFornecedoresp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btFornecedoresp.setText("Fornecedores");
        btFornecedoresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorespActionPerformed(evt);
            }
        });
        getContentPane().add(btFornecedoresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 52, 110, -1));

        btLojasp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btLojasp.setText("Lojas");
        btLojasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLojaspActionPerformed(evt);
            }
        });
        getContentPane().add(btLojasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 52, 110, -1));

        lItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lItem.setText("Item:");
        getContentPane().add(lItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        txtItem.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 400, 25));

        lCodigoproduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lCodigoproduto.setText("Código do Produto:");
        getContentPane().add(lCodigoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        txtCodigodoproduto.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txtCodigodoproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigodoprodutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigodoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 250, 25));

        lUnidadedemedida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lUnidadedemedida.setText("Unidade de Medida: (UND,CAIXA)");
        getContentPane().add(lUnidadedemedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        getContentPane().add(txtUnidadedemedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 250, 25));

        lEstoqueminimo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lEstoqueminimo.setText("Estoque Mínimo:");
        getContentPane().add(lEstoqueminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        getContentPane().add(txtEstoqueminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 250, 25));

        lCustounitario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lCustounitario.setText("Custo Unitário:");
        getContentPane().add(lCustounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        txtCustounitario.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(txtCustounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 250, 25));

        lPrecounitario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lPrecounitario.setText("Preço Unitário:");
        getContentPane().add(lPrecounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        txtPrecounitario.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(txtPrecounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 250, 25));

        btSalvarp.setBackground(new java.awt.Color(121, 218, 247));
        btSalvarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_1.png"))); // NOI18N
        btSalvarp.setBorder(null);
        btSalvarp.setContentAreaFilled(false);
        btSalvarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarpActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        btAlterarp.setBackground(new java.awt.Color(121, 218, 247));
        btAlterarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        btAlterarp.setBorder(null);
        btAlterarp.setContentAreaFilled(false);
        btAlterarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarpActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        btConsultarp.setBackground(new java.awt.Color(121, 218, 247));
        btConsultarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultar.png"))); // NOI18N
        btConsultarp.setBorder(null);
        btConsultarp.setContentAreaFilled(false);
        btConsultarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarpActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        btExcluirp.setBackground(new java.awt.Color(121, 218, 247));
        btExcluirp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btExcluirp.setBorder(null);
        btExcluirp.setContentAreaFilled(false);
        btExcluirp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirpActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluirp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        btInicial.setBackground(new java.awt.Color(121, 218, 247));
        btInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        btInicial.setBorder(null);
        btInicial.setContentAreaFilled(false);
        btInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 12, 50, 50));

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(85, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        jLabel3.setBackground(new java.awt.Color(153, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundinho_1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        tabelaProdutos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item", "Código do Produto", "Unidade de Medida", "Estoque Mínimo", "Custo Unitário", "Preço Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setDropMode(javax.swing.DropMode.ON);
        tabelaProdutos.setFocusCycleRoot(true);
        tabelaProdutos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaProdutosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 630, 220));

        setBounds(0, 0, 643, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void btFornecedorespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorespActionPerformed
        this.dispose();//fecha o form atual aberto
        CadastroFornecedor cf = new CadastroFornecedor();
        cf.setVisible(true);
    }//GEN-LAST:event_btFornecedorespActionPerformed

    private void btLojaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLojaspActionPerformed
        this.dispose();//fecha o form atual aberto
        CadastroLoja cl = new CadastroLoja();
        cl.setVisible(true);
    }//GEN-LAST:event_btLojaspActionPerformed

    private void btProdutospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutospActionPerformed
        JOptionPane.showMessageDialog(null, "Você já está no cadastro produtos");
    }//GEN-LAST:event_btProdutospActionPerformed

    private void btInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicialActionPerformed
        this.dispose();//fecha o form atual aberto
        Controle c = new Controle();
        c.setVisible(true);
    }//GEN-LAST:event_btInicialActionPerformed

    private void btSalvarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarpActionPerformed
        String item, unidadedemedida;
        int estoqueminimo;
        int codigoproduto;
        double custounitario;
        double precounitario;

        item = txtItem.getText();
        codigoproduto = Integer.parseInt(txtCodigodoproduto.getText());
        custounitario = Double.parseDouble(txtCustounitario.getText());
        precounitario = Double.parseDouble(txtPrecounitario.getText());
        unidadedemedida = txtUnidadedemedida.getText();
        estoqueminimo = Integer.parseInt(txtEstoqueminimo.getText());

        if (codigoproduto == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Código do Produto obrigatório!");
        }
        if (item.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Item obrigatório!");
        }
        if (custounitario == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Custo Unitário obrigatório!");
        }
        if (precounitario == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Preço Unitário obrigatório!");
        } else if (unidadedemedida.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Unidade de Medida obrigatório!");
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }

        CadastroProdutosDTO cpdto = new CadastroProdutosDTO();
        cpdto.setItem(item);
        cpdto.setCodigoProduto(codigoproduto);
        cpdto.setCustoUnitario(custounitario);
        cpdto.setPrecoUnitario(precounitario);
        cpdto.setUnidadeDeMedida(unidadedemedida);
        cpdto.setEstoqueMinimo(estoqueminimo);

        CadastroProdutosDAO cpdao = new CadastroProdutosDAO();
        cpdao.cadastroProdutodao(cpdto);


    }//GEN-LAST:event_btSalvarpActionPerformed

    private void txtCodigodoprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigodoprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigodoprodutoActionPerformed

    private void tabelaProdutosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaProdutosAncestorAdded

    }//GEN-LAST:event_tabelaProdutosAncestorAdded

    private void btConsultarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarpActionPerformed
        listarValoresProdutos();
        
    }//GEN-LAST:event_btConsultarpActionPerformed

    private void btAlterarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarpActionPerformed
        AlterarCadastroProdutos();
        listarValoresProdutos();
        LimparCampos();
    }//GEN-LAST:event_btAlterarpActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btExcluirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirpActionPerformed
        ExcluirCadastroProdutos();
        listarValoresProdutos();
        LimparCampos();
    }//GEN-LAST:event_btExcluirpActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarp;
    private javax.swing.JButton btConsultarp;
    private javax.swing.JButton btExcluirp;
    private javax.swing.JButton btFornecedoresp;
    private javax.swing.JButton btInicial;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLojasp;
    private javax.swing.JButton btProdutosp;
    private javax.swing.JButton btSalvarp;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCodigoproduto;
    private javax.swing.JLabel lCustounitario;
    private javax.swing.JLabel lEstoqueminimo;
    private javax.swing.JLabel lItem;
    private javax.swing.JLabel lPrecounitario;
    private javax.swing.JLabel lTitulocadastrodeprodutos;
    private javax.swing.JLabel lUnidadedemedida;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtCodigodoproduto;
    private javax.swing.JTextField txtCustounitario;
    private javax.swing.JTextField txtEstoqueminimo;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtPrecounitario;
    private javax.swing.JTextField txtUnidadedemedida;
    // End of variables declaration//GEN-END:variables

    private void listarValoresProdutos() {
        try {
            CadastroProdutosDAO objCadastroprodutosDAO = new CadastroProdutosDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();
            model.setNumRows(0);

            ArrayList<CadastroProdutosDTO> lista = objCadastroprodutosDAO.pesquisarCadastroProdutos();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getItem(),
                    lista.get(num).getCodigoProduto(),
                    lista.get(num).getUnidadeDeMedida(),
                    lista.get(num).getEstoqueMinimo(),
                    lista.get(num).getCustoUnitario(),
                    lista.get(num).getPrecoUnitario()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores tela Produto" + e.getMessage());
        }

    }
    
    private void AlterarCadastroProdutos(){
        String item, unidadedemedida;
        int estoqueminimo;
        int codigoproduto;
        double custounitario;
        double precounitario;
        
        codigoproduto = Integer.parseInt(txtCodigodoproduto.getText());
        item = txtItem.getText();
        unidadedemedida = txtUnidadedemedida.getText();
        estoqueminimo = Integer.parseInt(txtEstoqueminimo.getText());
        custounitario = Double.parseDouble(txtCustounitario.getText());
        precounitario = Double.parseDouble(txtPrecounitario.getText());
        
        
        CadastroProdutosDTO objcpdto = new CadastroProdutosDTO();
        objcpdto.setCodigoProduto(codigoproduto);
        objcpdto.setItem(item);
        objcpdto.setUnidadeDeMedida(unidadedemedida);
        objcpdto.setEstoqueMinimo(estoqueminimo);
        objcpdto.setCustoUnitario(custounitario);
        objcpdto.setPrecoUnitario(precounitario);
        

        CadastroProdutosDAO cpdao = new CadastroProdutosDAO();
        cpdao.alterarCadastroProdutos(objcpdto);
    }
    
     private void ExcluirCadastroProdutos(){
        String item, unidadedemedida;
        int estoqueminimo;
        int codigoproduto;
        double custounitario;
        double precounitario;
        
        codigoproduto = Integer.parseInt(txtCodigodoproduto.getText());
        item = txtItem.getText();
        unidadedemedida = txtUnidadedemedida.getText();
        estoqueminimo = Integer.parseInt(txtEstoqueminimo.getText());
        custounitario = Double.parseDouble(txtCustounitario.getText());
        precounitario = Double.parseDouble(txtPrecounitario.getText());
        
        
        CadastroProdutosDTO objcpdto = new CadastroProdutosDTO();
        objcpdto.setCodigoProduto(codigoproduto);
        objcpdto.setItem(item);
        objcpdto.setUnidadeDeMedida(unidadedemedida);
        objcpdto.setEstoqueMinimo(estoqueminimo);
        objcpdto.setCustoUnitario(custounitario);
        objcpdto.setPrecoUnitario(precounitario);
        

        CadastroProdutosDAO cpdao = new CadastroProdutosDAO();
        cpdao.excluirCadastroProdutos(objcpdto);
    }
     
    private void CarregarCampos(){
        int setar = tabelaProdutos.getSelectedRow();
        txtCodigodoproduto.setText(tabelaProdutos.getModel().getValueAt(setar,1).toString());
        txtItem.setText(tabelaProdutos.getModel().getValueAt(setar, 0).toString());
        txtUnidadedemedida.setText(tabelaProdutos.getModel().getValueAt(setar, 2).toString());
        txtEstoqueminimo.setText(tabelaProdutos.getModel().getValueAt(setar, 3).toString());
        txtCustounitario.setText(tabelaProdutos.getModel().getValueAt(setar, 4).toString());
        txtPrecounitario.setText(tabelaProdutos.getModel().getValueAt(setar, 5).toString());
    }
    private void LimparCampos(){
        txtCodigodoproduto.setText("");
        txtItem.setText("");
        txtUnidadedemedida.setText("");
        txtEstoqueminimo.setText("");
        txtCustounitario.setText("");
        txtPrecounitario.setText("");
        
    }
}
