/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Manenhos
 */
public class Controle extends javax.swing.JFrame {

    /**
     * Creates new form Controle
     */
    public Controle() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Teladelogin.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btCadastrodedados = new javax.swing.JButton();
        btControledeentradas = new javax.swing.JButton();
        Controledesaidas = new javax.swing.JButton();
        btControledeestoque = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 441));
        setPreferredSize(new java.awt.Dimension(630, 441));
        setSize(new java.awt.Dimension(630, 441));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Controle de Estoque");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 70, 311, 42);

        btCadastrodedados.setBackground(new java.awt.Color(121, 218, 247));
        btCadastrodedados.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btCadastrodedados.setForeground(new java.awt.Color(0, 0, 0));
        btCadastrodedados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrar.png"))); // NOI18N
        btCadastrodedados.setText("<html>\n<p text-aling: center>Cadastro<br> \nde Dados <br></p>\n</html>");
        btCadastrodedados.setActionCommand("Cadastro \nde \nDados ");
        btCadastrodedados.setBorder(null);
        btCadastrodedados.setContentAreaFilled(false);
        btCadastrodedados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrodedadosActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrodedados);
        btCadastrodedados.setBounds(150, 150, 130, 50);

        btControledeentradas.setBackground(new java.awt.Color(121, 218, 247));
        btControledeentradas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btControledeentradas.setForeground(new java.awt.Color(0, 0, 0));
        btControledeentradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrar.png"))); // NOI18N
        btControledeentradas.setText("<html>\n<p txt-aling:center>\nControle de \nEntradas</p>\n</html>");
        btControledeentradas.setBorder(null);
        btControledeentradas.setContentAreaFilled(false);
        btControledeentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btControledeentradasActionPerformed(evt);
            }
        });
        getContentPane().add(btControledeentradas);
        btControledeentradas.setBounds(140, 240, 150, 50);

        Controledesaidas.setBackground(new java.awt.Color(121, 218, 247));
        Controledesaidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Controledesaidas.setForeground(new java.awt.Color(0, 0, 0));
        Controledesaidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        Controledesaidas.setText("<html> <p text-aling:center>Controle de <br> Saídas</p> </html>");
        Controledesaidas.setBorder(null);
        Controledesaidas.setContentAreaFilled(false);
        Controledesaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControledesaidasActionPerformed(evt);
            }
        });
        getContentPane().add(Controledesaidas);
        Controledesaidas.setBounds(330, 240, 144, 50);

        btControledeestoque.setBackground(new java.awt.Color(121, 218, 247));
        btControledeestoque.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btControledeestoque.setForeground(new java.awt.Color(0, 0, 0));
        btControledeestoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque.png"))); // NOI18N
        btControledeestoque.setText("<html> <p text-aling:center>Controle de<br>  Estoque</p> </html>");
        btControledeestoque.setBorder(null);
        btControledeestoque.setContentAreaFilled(false);
        btControledeestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btControledeestoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btControledeestoque);
        btControledeestoque.setBounds(330, 150, 145, 50);

        btSair.setBackground(new java.awt.Color(121, 218, 247));
        btSair.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICON.png"))); // NOI18N
        btSair.setBorder(null);
        btSair.setContentAreaFilled(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(290, 320, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundinho_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -5, 630, 450);

        setBounds(0, 0, 643, 481);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrodedadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrodedadosActionPerformed
        this.dispose();//fecha o form atual aberto
            CadastroProdutos cdp= new CadastroProdutos();
            cdp.setVisible(true);
    }//GEN-LAST:event_btCadastrodedadosActionPerformed

    private void btControledeestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btControledeestoqueActionPerformed
        this.dispose();//fecha o form atual aberto
            ControleDeEstoque cde= new ControleDeEstoque();
            cde.setVisible(true);
    }//GEN-LAST:event_btControledeestoqueActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btControledeentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btControledeentradasActionPerformed
        this.dispose();//fecha o form atual aberto
            ControleEntrada cde= new ControleEntrada();
            cde.setVisible(true);
    }//GEN-LAST:event_btControledeentradasActionPerformed

    private void ControledesaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControledesaidasActionPerformed
        this.dispose();//fecha o form atual aberto
            ControleSaida cde= new ControleSaida();
            cde.setVisible(true);
    }//GEN-LAST:event_ControledesaidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Controledesaidas;
    private javax.swing.JButton btCadastrodedados;
    private javax.swing.JButton btControledeentradas;
    private javax.swing.JButton btControledeestoque;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
