/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Dao.CadastroLojaDAO;
import Dao.ControleEntradaDAO;
import Dao.ControleSaidaDAO;
import Dto.CadastroLojaDTO;
import Dto.ControleEntradaDTO;
import Dto.ControleSaidaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manenhos
 */
public class ControleSaida extends javax.swing.JFrame {

    /**
     * Creates new form ControleSaida1
     */
    public ControleSaida() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(CadastroProdutos.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lvalorcompratotal = new javax.swing.JLabel();
        lcodfornecedors = new javax.swing.JLabel();
        btSelecionar = new javax.swing.JButton();
        txtValordevendatotal = new javax.swing.JTextField();
        ldatavenda = new javax.swing.JLabel();
        txtCodigodaloja = new javax.swing.JTextField();
        ftDatadavenda = new javax.swing.JFormattedTextField();
        lempresas = new javax.swing.JLabel();
        lcodprodutos = new javax.swing.JLabel();
        txtLoja = new javax.swing.JTextField();
        txtCodigodoprodutos = new javax.swing.JTextField();
        lquantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lnomeprodutos = new javax.swing.JLabel();
        lcustounitario = new javax.swing.JLabel();
        txtNomedoprodutos = new javax.swing.JTextField();
        txtPrecounitario = new javax.swing.JTextField();
        lTitulocontroledesaidas = new javax.swing.JLabel();
        btInicial = new javax.swing.JButton();
        btExcluirp = new javax.swing.JButton();
        btConsultarp = new javax.swing.JButton();
        btAlterarp = new javax.swing.JButton();
        btSalvarp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigosaida = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSaida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(630, 441));
        setMinimumSize(new java.awt.Dimension(630, 441));
        setPreferredSize(new java.awt.Dimension(630, 441));
        setSize(new java.awt.Dimension(630, 441));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lvalorcompratotal.setText("Valor de venda total:");
        getContentPane().add(lvalorcompratotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        lcodfornecedors.setText("Código do loja:");
        getContentPane().add(lcodfornecedors, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));
        getContentPane().add(txtValordevendatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 120, 25));

        ldatavenda.setText("Data da venda:");
        getContentPane().add(ldatavenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        getContentPane().add(txtCodigodaloja, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, 25));

        ftDatadavenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(ftDatadavenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, 25));

        lempresas.setText("Loja:");
        getContentPane().add(lempresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        lcodprodutos.setText("Código do produto:");
        getContentPane().add(lcodprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));
        getContentPane().add(txtLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 25));
        getContentPane().add(txtCodigodoprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, 25));

        lquantidade.setText("Quantidade vendida:");
        getContentPane().add(lquantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 120, 25));

        lnomeprodutos.setText("Nome do produto:");
        getContentPane().add(lnomeprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        lcustounitario.setText("Preço unitário:");
        getContentPane().add(lcustounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));
        getContentPane().add(txtNomedoprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 200, 25));
        getContentPane().add(txtPrecounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 120, 25));

        lTitulocontroledesaidas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lTitulocontroledesaidas.setText("CONTROLE DE SAIDAS");
        getContentPane().add(lTitulocontroledesaidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 12, -1, -1));

        btInicial.setBackground(new java.awt.Color(121, 218, 247));
        btInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        btInicial.setBorder(null);
        btInicial.setContentAreaFilled(false);
        btInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 12, 50, 50));

        btExcluirp.setBackground(new java.awt.Color(121, 218, 247));
        btExcluirp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btExcluirp.setBorder(null);
        btExcluirp.setContentAreaFilled(false);
        btExcluirp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirpActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluirp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        btConsultarp.setBackground(new java.awt.Color(121, 218, 247));
        btConsultarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultar.png"))); // NOI18N
        btConsultarp.setBorder(null);
        btConsultarp.setContentAreaFilled(false);
        btConsultarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarpActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        btAlterarp.setBackground(new java.awt.Color(121, 218, 247));
        btAlterarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        btAlterarp.setBorder(null);
        btAlterarp.setContentAreaFilled(false);
        btAlterarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarpActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        btSalvarp.setBackground(new java.awt.Color(121, 218, 247));
        btSalvarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_1.png"))); // NOI18N
        btSalvarp.setBorder(null);
        btSalvarp.setContentAreaFilled(false);
        btSalvarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarpActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel1.setText("Código Saida:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txtCodigosaida.setEnabled(false);
        getContentPane().add(txtCodigosaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, -1));

        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(85, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundinho_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 630, 450));

        tabelaSaida.setAutoCreateRowSorter(true);
        tabelaSaida.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabelaSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod.Saida","Data da Venda", "Cod.Produto", "Nome da Produto", "Cod.Loja", "Loja", "Quantidade Vendida", "Preço Unitário", "Valor de Venda Total"
            }
        ));
        jScrollPane1.setViewportView(tabelaSaida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 630, 240));

        setBounds(0, 0, 644, 717);
    }// </editor-fold>//GEN-END:initComponents

    private void btInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicialActionPerformed
        this.dispose();//fecha o form atual aberto
            Controle c= new Controle();
            c.setVisible(true);
    }//GEN-LAST:event_btInicialActionPerformed

    private void btSalvarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarpActionPerformed
        String datavenda, nomedoproduto, loja;
        int quantidadevendida, codigoproduto, codigoloja, codigosaida;
        double valorvendatotal, precounitario;

        //codigosaida = Integer.parseInt(txtCodigosaida.getText()); 
        datavenda = ftDatadavenda.getText();
        nomedoproduto = txtNomedoprodutos.getText();
        loja = txtLoja.getText();
        quantidadevendida = Integer.parseInt(txtQuantidade.getText());
        precounitario = Double.parseDouble(txtPrecounitario.getText());
        valorvendatotal = Double.parseDouble(txtValordevendatotal.getText());
        codigoproduto = Integer.parseInt(txtCodigodoprodutos.getText());
        codigoloja = Integer.parseInt(txtCodigodaloja.getText());
      

        ControleSaidaDTO objcadastrosaidadto = new ControleSaidaDTO();
        objcadastrosaidadto.setDataVenda(datavenda); 
        objcadastrosaidadto.setNomeDoProduto(nomedoproduto);
        objcadastrosaidadto.setLoja(loja);
        objcadastrosaidadto.setQuantidadeVendida(quantidadevendida);
        objcadastrosaidadto.setValorVendaTotal(valorvendatotal);
        objcadastrosaidadto.setPrecoUnitario(precounitario);
        objcadastrosaidadto.setCodigoProduto(codigoproduto);
        objcadastrosaidadto.setCodigoLoja(codigoloja);
        //objcadastrosaidadto.setCodigoSaida(codigosaida);

        if (codigoproduto == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Codigo Produto obrigatório!");
        }
        if (codigoloja == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Codigo Loja obrigatório!");
        }
        if (quantidadevendida == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Quantidade Vendida obrigatório!");
        }
        if (loja.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Loja obrigatório!");
        }
        if (nomedoproduto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Nome do Produto obrigatório!");
        }
        if (datavenda.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento da Data de Venda obrigatório!");
        }
        if (valorvendatotal == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Total Vendido obrigatório!");
        } else if (precounitario == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Preço Unitário obrigatório!");
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }

        ControleSaidaDAO objcontrolesaidadao = new ControleSaidaDAO();
        objcontrolesaidadao.cadastroSaidadao(objcadastrosaidadto);
    }//GEN-LAST:event_btSalvarpActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarpActionPerformed
        AlterarControleSaida();
        listarValoresSaida();
        LimparCampos();
    }//GEN-LAST:event_btAlterarpActionPerformed

    private void btConsultarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarpActionPerformed
        listarValoresSaida();
    }//GEN-LAST:event_btConsultarpActionPerformed

    private void btExcluirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirpActionPerformed
        ExcluirControleEntrada();
        listarValoresSaida();
        LimparCampos();
    }//GEN-LAST:event_btExcluirpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarp;
    private javax.swing.JButton btConsultarp;
    private javax.swing.JButton btExcluirp;
    private javax.swing.JButton btInicial;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvarp;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JFormattedTextField ftDatadavenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTitulocontroledesaidas;
    private javax.swing.JLabel lcodfornecedors;
    private javax.swing.JLabel lcodprodutos;
    private javax.swing.JLabel lcustounitario;
    private javax.swing.JLabel ldatavenda;
    private javax.swing.JLabel lempresas;
    private javax.swing.JLabel lnomeprodutos;
    private javax.swing.JLabel lquantidade;
    private javax.swing.JLabel lvalorcompratotal;
    private javax.swing.JTable tabelaSaida;
    private javax.swing.JTextField txtCodigodaloja;
    private javax.swing.JTextField txtCodigodoprodutos;
    private javax.swing.JTextField txtCodigosaida;
    private javax.swing.JTextField txtLoja;
    private javax.swing.JTextField txtNomedoprodutos;
    private javax.swing.JTextField txtPrecounitario;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValordevendatotal;
    // End of variables declaration//GEN-END:variables

    private void listarValoresSaida() {
        try {
            ControleSaidaDAO objControleSaidaDAO = new ControleSaidaDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaSaida.getModel();
            model.setNumRows(0);

            ArrayList<ControleSaidaDTO> lista = objControleSaidaDAO.pesquisarControleSaida();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCodigoSaida(),
                    lista.get(num).getDataVenda(),
                    lista.get(num).getCodigoProduto(),
                    lista.get(num).getNomeDoProduto(),
                    lista.get(num).getCodigoLoja(),
                    lista.get(num).getLoja(),
                    lista.get(num).getQuantidadeVendida(),
                    lista.get(num).getPrecoUnitario(),
                    lista.get(num).getValorVendaTotal()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores tela Saida" + e.getMessage());
        }
    }
    private void AlterarControleSaida(){
        String datavenda, nomedoproduto, loja;
        int quantidadevendida, codigoproduto, codigoloja, codigosaida;
        double valorvendatotal, precounitario;

        codigosaida = Integer.parseInt(txtCodigosaida.getText()); 
        datavenda = ftDatadavenda.getText();
        nomedoproduto = txtNomedoprodutos.getText();
        loja = txtLoja.getText();
        quantidadevendida = Integer.parseInt(txtQuantidade.getText());
        precounitario = Double.parseDouble(txtPrecounitario.getText());
        valorvendatotal = Double.parseDouble(txtValordevendatotal.getText());
        codigoproduto = Integer.parseInt(txtCodigodoprodutos.getText());
        codigoloja = Integer.parseInt(txtCodigodaloja.getText());
      

        ControleSaidaDTO objcadastrosaidadto = new ControleSaidaDTO();
        objcadastrosaidadto.setDataVenda(datavenda); 
        objcadastrosaidadto.setNomeDoProduto(nomedoproduto);
        objcadastrosaidadto.setLoja(loja);
        objcadastrosaidadto.setQuantidadeVendida(quantidadevendida);
        objcadastrosaidadto.setValorVendaTotal(valorvendatotal);
        objcadastrosaidadto.setPrecoUnitario(precounitario);
        objcadastrosaidadto.setCodigoProduto(codigoproduto);
        objcadastrosaidadto.setCodigoLoja(codigoloja);
        objcadastrosaidadto.setCodigoSaida(codigosaida);
        
        ControleSaidaDAO objcontrolesaidadao = new ControleSaidaDAO();
        objcontrolesaidadao.alterarControleSaida(objcadastrosaidadto);
        
    }
    
     private void ExcluirControleEntrada(){
        String datavenda, nomedoproduto, loja;
        int quantidadevendida, codigoproduto, codigoloja, codigosaida;
        double valorvendatotal, precounitario;

        codigosaida = Integer.parseInt(txtCodigosaida.getText()); 
        datavenda = ftDatadavenda.getText();
        nomedoproduto = txtNomedoprodutos.getText();
        loja = txtLoja.getText();
        quantidadevendida = Integer.parseInt(txtQuantidade.getText());
        precounitario = Double.parseDouble(txtPrecounitario.getText());
        valorvendatotal = Double.parseDouble(txtValordevendatotal.getText());
        codigoproduto = Integer.parseInt(txtCodigodoprodutos.getText());
        codigoloja = Integer.parseInt(txtCodigodaloja.getText());
      

        ControleSaidaDTO objcadastrosaidadto = new ControleSaidaDTO();
        objcadastrosaidadto.setDataVenda(datavenda); 
        objcadastrosaidadto.setNomeDoProduto(nomedoproduto);
        objcadastrosaidadto.setLoja(loja);
        objcadastrosaidadto.setQuantidadeVendida(quantidadevendida);
        objcadastrosaidadto.setValorVendaTotal(valorvendatotal);
        objcadastrosaidadto.setPrecoUnitario(precounitario);
        objcadastrosaidadto.setCodigoProduto(codigoproduto);
        objcadastrosaidadto.setCodigoLoja(codigoloja);
        objcadastrosaidadto.setCodigoSaida(codigosaida);
        
        ControleSaidaDAO objcontrolesaidadao = new ControleSaidaDAO();
        objcontrolesaidadao.excluirControleSaida(objcadastrosaidadto);
    }
     
    private void CarregarCampos(){
        int setar = tabelaSaida.getSelectedRow();
        txtCodigosaida.setText(tabelaSaida.getModel().getValueAt(setar,0).toString());
        ftDatadavenda.setText(tabelaSaida.getModel().getValueAt(setar, 1).toString());
        txtCodigodoprodutos.setText(tabelaSaida.getModel().getValueAt(setar, 2).toString());
        txtNomedoprodutos.setText(tabelaSaida.getModel().getValueAt(setar, 3).toString());
        txtCodigodaloja.setText(tabelaSaida.getModel().getValueAt(setar, 4).toString());
        txtLoja.setText(tabelaSaida.getModel().getValueAt(setar, 5).toString());
        txtQuantidade.setText(tabelaSaida.getModel().getValueAt(setar, 6).toString());
        txtPrecounitario.setText(tabelaSaida.getModel().getValueAt(setar, 7).toString());
        txtValordevendatotal.setText(tabelaSaida.getModel().getValueAt(setar, 8).toString());
    }
    private void LimparCampos(){
        txtCodigosaida.setText("");
        ftDatadavenda.setText("");
        txtCodigodoprodutos.setText("");
        txtNomedoprodutos.setText("");
        txtCodigodaloja.setText("");
        txtLoja.setText("");
        txtQuantidade.setText("");
        txtPrecounitario.setText("");
        txtValordevendatotal.setText("");
        
    }
}
