/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Dao.ControleEntradaDAO;
import Dto.CadastroLojaDTO;
import Dto.ControleEntradaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manenhos
 */
public class ControleEntrada extends javax.swing.JFrame {

    /**
     * Creates new form ControleEntradas
     */
    public ControleEntrada() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(CadastroProdutos.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulocontroledeentradas = new javax.swing.JLabel();
        ldatacompra = new javax.swing.JLabel();
        ftDatadacompra = new javax.swing.JFormattedTextField();
        lcodproduto = new javax.swing.JLabel();
        txtCodigodoproduto = new javax.swing.JTextField();
        lnomeproduto = new javax.swing.JLabel();
        txtNomedoproduto = new javax.swing.JTextField();
        lcodfornecedor = new javax.swing.JLabel();
        txtCodigodofornecedor = new javax.swing.JTextField();
        lempresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        lquantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lcustounitario = new javax.swing.JLabel();
        txtCustounitario = new javax.swing.JTextField();
        lvalorcompratotal = new javax.swing.JLabel();
        txtValordecompratotal = new javax.swing.JTextField();
        btInicial = new javax.swing.JButton();
        btExcluirp = new javax.swing.JButton();
        btConsultarp = new javax.swing.JButton();
        btAlterarp = new javax.swing.JButton();
        btSalvarp = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoentrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEntrada = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 441));
        getContentPane().setLayout(null);

        lTitulocontroledeentradas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lTitulocontroledeentradas.setText("CONTROLE DE ENTRADAS");
        getContentPane().add(lTitulocontroledeentradas);
        lTitulocontroledeentradas.setBounds(154, 12, 310, 28);

        ldatacompra.setText("Data da compra:");
        getContentPane().add(ldatacompra);
        ldatacompra.setBounds(100, 110, 130, 15);

        ftDatadacompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(ftDatadacompra);
        ftDatadacompra.setBounds(100, 130, 120, 25);

        lcodproduto.setText("Código do produto:");
        getContentPane().add(lcodproduto);
        lcodproduto.setBounds(100, 170, 120, 15);
        getContentPane().add(txtCodigodoproduto);
        txtCodigodoproduto.setBounds(100, 190, 120, 25);

        lnomeproduto.setText("Nome do produto:");
        getContentPane().add(lnomeproduto);
        lnomeproduto.setBounds(260, 170, 110, 15);
        getContentPane().add(txtNomedoproduto);
        txtNomedoproduto.setBounds(260, 190, 200, 25);

        lcodfornecedor.setText("Código do fornecedor:");
        getContentPane().add(lcodfornecedor);
        lcodfornecedor.setBounds(100, 230, 130, 15);
        getContentPane().add(txtCodigodofornecedor);
        txtCodigodofornecedor.setBounds(100, 250, 120, 25);

        lempresa.setText("Empresa:");
        getContentPane().add(lempresa);
        lempresa.setBounds(260, 230, 60, 15);
        getContentPane().add(txtEmpresa);
        txtEmpresa.setBounds(260, 250, 200, 25);

        lquantidade.setText("Quantidade:");
        getContentPane().add(lquantidade);
        lquantidade.setBounds(100, 290, 80, 15);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(100, 310, 120, 25);

        lcustounitario.setText("Custo unitário:");
        getContentPane().add(lcustounitario);
        lcustounitario.setBounds(260, 290, 90, 15);
        getContentPane().add(txtCustounitario);
        txtCustounitario.setBounds(260, 310, 120, 25);

        lvalorcompratotal.setText("Valor de compra total:");
        getContentPane().add(lvalorcompratotal);
        lvalorcompratotal.setBounds(420, 290, 120, 15);
        getContentPane().add(txtValordecompratotal);
        txtValordecompratotal.setBounds(420, 310, 120, 25);

        btInicial.setBackground(new java.awt.Color(121, 218, 247));
        btInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        btInicial.setBorder(null);
        btInicial.setContentAreaFilled(false);
        btInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btInicial);
        btInicial.setBounds(542, 12, 50, 50);

        btExcluirp.setBackground(new java.awt.Color(121, 218, 247));
        btExcluirp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btExcluirp.setBorder(null);
        btExcluirp.setContentAreaFilled(false);
        btExcluirp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirpActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluirp);
        btExcluirp.setBounds(380, 390, 25, 24);

        btConsultarp.setBackground(new java.awt.Color(121, 218, 247));
        btConsultarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultar.png"))); // NOI18N
        btConsultarp.setBorder(null);
        btConsultarp.setContentAreaFilled(false);
        btConsultarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarpActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarp);
        btConsultarp.setBounds(280, 390, 25, 25);

        btAlterarp.setBackground(new java.awt.Color(121, 218, 247));
        btAlterarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        btAlterarp.setBorder(null);
        btAlterarp.setContentAreaFilled(false);
        btAlterarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarpActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterarp);
        btAlterarp.setBounds(190, 390, 24, 25);

        btSalvarp.setBackground(new java.awt.Color(121, 218, 247));
        btSalvarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_1.png"))); // NOI18N
        btSalvarp.setBorder(null);
        btSalvarp.setContentAreaFilled(false);
        btSalvarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarpActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarp);
        btSalvarp.setBounds(110, 390, 24, 25);

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btSelecionar);
        btSelecionar.setBounds(450, 360, 85, 25);

        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(85, 25));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(450, 390, 85, 25);

        jLabel1.setText("Código Entrada:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 100, 15);

        txtCodigoentrada.setEnabled(false);
        getContentPane().add(txtCodigoentrada);
        txtCodigoentrada.setBounds(100, 80, 70, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundinho_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 630, 460);

        tabelaEntrada.setAutoCreateRowSorter(true);
        tabelaEntrada.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabelaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod.Entrada","Data da Compra", "Cod.Produto", "Nome do Produto", "Cod.Fornecedor", "Empresa", "Quantidade", "Custo Unitário", "Valor de Compra Total"
            }
        ));
        tabelaEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaEntradaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelaEntrada);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 440, 630, 230);

        setBounds(0, 0, 642, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void btInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicialActionPerformed
        this.dispose();//fecha o form atual aberto
            Controle c= new Controle();
            c.setVisible(true);
    }//GEN-LAST:event_btInicialActionPerformed

    private void btSalvarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarpActionPerformed
        
        String datacompra, nomedoproduto, empresa;
        int quantidade, codigoproduto, codigofornecedor;
        double valorcompratotal, custounitario;
        
        //codigoentrada = Integer.parseInt(txtCodigoentrada.getText()); 
        datacompra = ftDatadacompra.getText();
        nomedoproduto = txtNomedoproduto.getText();
        empresa = txtEmpresa.getText();
        quantidade = Integer.parseInt(txtQuantidade.getText());
        custounitario = Double.parseDouble(txtCustounitario.getText());
        valorcompratotal = Double.parseDouble(txtValordecompratotal.getText());
        codigoproduto = Integer.parseInt(txtCodigodoproduto.getText());
        codigofornecedor = Integer.parseInt(txtCodigodofornecedor.getText());
      

        ControleEntradaDTO objcadastroentradadto = new ControleEntradaDTO();
        
        objcadastroentradadto.setDataCompra(datacompra); 
        objcadastroentradadto.setNomeDoProduto(nomedoproduto);
        objcadastroentradadto.setEmpresa(empresa);
        objcadastroentradadto.setQuantidade(quantidade);
        objcadastroentradadto.setValorCompraTotal(valorcompratotal);
        objcadastroentradadto.setCustoUnitario(custounitario);
        objcadastroentradadto.setCodigoProduto(codigoproduto);
        objcadastroentradadto.setCodigoFornecedor(codigofornecedor);
        //objcadastroentradadto.setCodigoEntrada(codigoentrada); 

        if (codigoproduto == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Codigo Produto obrigatório!");
        }
        if (codigofornecedor == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Codigo Fornecedor obrigatório!");
        }
        if (quantidade == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Quantidade obrigatório!");
        }
        if (empresa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Empresa obrigatório!");
        }
        if (nomedoproduto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Nome do Produto obrigatório!");
        }
        if (datacompra.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchimento da Data da Compra obrigatório!");
        }
        if (valorcompratotal == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Total Comprado obrigatório!");
        } else if (custounitario == 0) {
            JOptionPane.showMessageDialog(null, "Preenchimento do Custo Unitário obrigatório!");
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }

        ControleEntradaDAO objcontroleentradadao = new ControleEntradaDAO();
        objcontroleentradadao.cadastroEntradadao(objcadastroentradadto);
    }//GEN-LAST:event_btSalvarpActionPerformed

    private void tabelaEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaEntradaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaEntradaAncestorAdded

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarpActionPerformed
        AlterarControleEntrada();
        listarValoresEstoque();
        LimparCampos();
    }//GEN-LAST:event_btAlterarpActionPerformed

    private void btExcluirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirpActionPerformed
        ExcluirControleEntrada();
        listarValoresEstoque();
        LimparCampos();
    }//GEN-LAST:event_btExcluirpActionPerformed

    private void btConsultarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarpActionPerformed
        listarValoresEstoque();
    }//GEN-LAST:event_btConsultarpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarp;
    private javax.swing.JButton btConsultarp;
    private javax.swing.JButton btExcluirp;
    private javax.swing.JButton btInicial;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvarp;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JFormattedTextField ftDatadacompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTitulocontroledeentradas;
    private javax.swing.JLabel lcodfornecedor;
    private javax.swing.JLabel lcodproduto;
    private javax.swing.JLabel lcustounitario;
    private javax.swing.JLabel ldatacompra;
    private javax.swing.JLabel lempresa;
    private javax.swing.JLabel lnomeproduto;
    private javax.swing.JLabel lquantidade;
    private javax.swing.JLabel lvalorcompratotal;
    private javax.swing.JTable tabelaEntrada;
    private javax.swing.JTextField txtCodigodofornecedor;
    private javax.swing.JTextField txtCodigodoproduto;
    private javax.swing.JTextField txtCodigoentrada;
    private javax.swing.JTextField txtCustounitario;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNomedoproduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValordecompratotal;
    // End of variables declaration//GEN-END:variables

    private void listarValoresEstoque() {
        try {
            ControleEntradaDAO objControleEntradaDAO = new ControleEntradaDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaEntrada.getModel();
            model.setNumRows(0);

            ArrayList<ControleEntradaDTO> lista = objControleEntradaDAO.pesquisarControleEntrada();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCodigoEntrada(),
                    lista.get(num).getDataCompra(),
                    lista.get(num).getCodigoProduto(),
                    lista.get(num).getNomeDoProduto(),
                    lista.get(num).getCodigoFornecedor(),
                    lista.get(num).getEmpresa(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getCustoUnitario(),
                    lista.get(num).getValorCompraTotal()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores tela Entrada" + e.getMessage());
        }
    }
    private void AlterarControleEntrada(){
        String datacompra, nomedoproduto, empresa;
        int quantidade, codigoproduto, codigofornecedor, codigoentrada;
        double valorcompratotal, custounitario;
        
        codigoentrada = Integer.parseInt(txtCodigoentrada.getText()); 
        datacompra = ftDatadacompra.getText();
        nomedoproduto = txtNomedoproduto.getText();
        empresa = txtEmpresa.getText();
        quantidade = Integer.parseInt(txtQuantidade.getText());
        custounitario = Double.parseDouble(txtCustounitario.getText());
        valorcompratotal = Double.parseDouble(txtValordecompratotal.getText());
        codigoproduto = Integer.parseInt(txtCodigodoproduto.getText());
        codigofornecedor = Integer.parseInt(txtCodigodofornecedor.getText());
      

        ControleEntradaDTO objcadastroentradadto = new ControleEntradaDTO();
        
        objcadastroentradadto.setDataCompra(datacompra); 
        objcadastroentradadto.setNomeDoProduto(nomedoproduto);
        objcadastroentradadto.setEmpresa(empresa);
        objcadastroentradadto.setQuantidade(quantidade);
        objcadastroentradadto.setValorCompraTotal(valorcompratotal);
        objcadastroentradadto.setCustoUnitario(custounitario);
        objcadastroentradadto.setCodigoProduto(codigoproduto);
        objcadastroentradadto.setCodigoFornecedor(codigofornecedor);
        objcadastroentradadto.setCodigoEntrada(codigoentrada); 
        
        ControleEntradaDAO objcontroleentradadao = new ControleEntradaDAO();
        objcontroleentradadao.alterarControleEntrada(objcadastroentradadto);
    }
    
     private void ExcluirControleEntrada(){
        String datacompra, nomedoproduto, empresa;
        int quantidade, codigoproduto, codigofornecedor, codigoentrada;
        double valorcompratotal, custounitario;
        
        codigoentrada = Integer.parseInt(txtCodigoentrada.getText()); 
        datacompra = ftDatadacompra.getText();
        nomedoproduto = txtNomedoproduto.getText();
        empresa = txtEmpresa.getText();
        quantidade = Integer.parseInt(txtQuantidade.getText());
        custounitario = Double.parseDouble(txtCustounitario.getText());
        valorcompratotal = Double.parseDouble(txtValordecompratotal.getText());
        codigoproduto = Integer.parseInt(txtCodigodoproduto.getText());
        codigofornecedor = Integer.parseInt(txtCodigodofornecedor.getText());
      

        ControleEntradaDTO objcadastroentradadto = new ControleEntradaDTO();
        
        objcadastroentradadto.setDataCompra(datacompra); 
        objcadastroentradadto.setNomeDoProduto(nomedoproduto);
        objcadastroentradadto.setEmpresa(empresa);
        objcadastroentradadto.setQuantidade(quantidade);
        objcadastroentradadto.setValorCompraTotal(valorcompratotal);
        objcadastroentradadto.setCustoUnitario(custounitario);
        objcadastroentradadto.setCodigoProduto(codigoproduto);
        objcadastroentradadto.setCodigoFornecedor(codigofornecedor);
        objcadastroentradadto.setCodigoEntrada(codigoentrada); 
        
        ControleEntradaDAO objcontroleentradadao = new ControleEntradaDAO();
        objcontroleentradadao.excluirControleEntrada(objcadastroentradadto);
    }
     
    private void CarregarCampos(){
        int setar = tabelaEntrada.getSelectedRow();
        txtCodigoentrada.setText(tabelaEntrada.getModel().getValueAt(setar,0).toString());
        ftDatadacompra.setText(tabelaEntrada.getModel().getValueAt(setar, 1).toString());
        txtCodigodoproduto.setText(tabelaEntrada.getModel().getValueAt(setar, 2).toString());
        txtNomedoproduto.setText(tabelaEntrada.getModel().getValueAt(setar, 3).toString());
        txtCodigodofornecedor.setText(tabelaEntrada.getModel().getValueAt(setar, 4).toString());
        txtEmpresa.setText(tabelaEntrada.getModel().getValueAt(setar, 5).toString());
        txtQuantidade.setText(tabelaEntrada.getModel().getValueAt(setar, 6).toString());
        txtCustounitario.setText(tabelaEntrada.getModel().getValueAt(setar, 7).toString());
        txtValordecompratotal.setText(tabelaEntrada.getModel().getValueAt(setar, 8).toString());
    }
    private void LimparCampos(){
        txtCodigoentrada.setText("");
        ftDatadacompra.setText("");
        txtCodigodoproduto.setText("");
        txtNomedoproduto.setText("");
        txtCodigodofornecedor.setText("");
        txtEmpresa.setText("");
        txtQuantidade.setText("");
        txtCustounitario.setText("");
        txtValordecompratotal.setText("");
        
    }
}
